# Generated by Django 4.2.6 on 2023-10-12 15:10

from django.db import migrations, models

import apps.base.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('count', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Price')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SALE', 'Sale')], default=apps.base.enums.OrderType['BUY'], max_length=10, verbose_name='Type')),
                ('finished_at', models.DateTimeField(default=None, null=True, verbose_name='Finished at')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default=apps.base.enums.OrderStatus['IN_PROGRESS'], max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
    ]
