# Generated by Django 4.2.6 on 2023-10-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_role"),
        ("order", "0002_remove_order_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wallet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.wallet",
            ),
            preserve_default=False,
        ),
    ]
