# Generated by Django 4.2.6 on 2023-10-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("CANCELED", "Canceled"),
                ],
                default="IN_PROGRESS",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SALE", "Sale")],
                default="BUY",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
