repos:
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v5.10.1'
      hooks:
        - id: isort
          args: [
            '--settings', 'lint-configs/.isort.cfg',
          ]

  -   repo: https://github.com/pycqa/flake8.git
      rev: '6.1.0'
      hooks:
        - id: flake8
          args: [
            '--config', 'lint-configs/.flake8',
          ]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.5.1'
      hooks:
        -   id: mypy
            args: [
              '--config-file', 'lint-configs/mypy.ini'
            ]

  -   repo: https://github.com/pre-commit/mirrors-pylint
      rev: 'v3.0.0a5'
      hooks:
        -   id: pylint
            args: [
              '--rcfile', 'lint-configs/.pylintrc'
            ]
