version: '3.9'

services:
#
#  db:
#    image: postgres
#    ports:
#      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
#      - "4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=lambda,s3,ses
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
