version: '3.9'

services:
  app:
    depends_on:
     - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    volumes:
      - .:/trading_django/
    entrypoint: ./entrypoint-django.sh
    healthcheck:
      test: curl --fail http://localhost:8000/admin/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - default

  localstack:
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}"            # LocalStack Gateway
#      - "4510-4559:4510-4559"  # external services port range
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - default

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker
    entrypoint: ./entrypoint-celery-worker.sh
    volumes:
      - .:/trading_django/
    env_file:
      - .env
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_started
      schedule:
        condition: service_started
    networks:
      - default

  schedule:
    build:
      context: .
    hostname: schedule
    entrypoint: ./entrypoint-celery-schedule.sh
    volumes:
      - .:/trading_django/
    env_file:
      - .env
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - default

  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - default

  redis:
    image: redis
    restart: always
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: trading