# Generated by Django 4.2.6 on 2023-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price_for_buy', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price for buy')),
                ('price_for_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price for buy')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currency',
            },
        ),
    ]
