# Generated by Django 4.2.6 on 2023-10-13 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="deleted_at",
        ),
    ]
