# Generated by Django 4.2.6 on 2023-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_remove_currency_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="currencies/"
            ),
        ),
    ]
