# Generated by Django 4.2.6 on 2023-10-31 16:51

import storages.backends.s3
from django.db import migrations, models

import apps.base.utils


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0003_currency_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=apps.base.utils.upload_to,
            ),
        ),
    ]
