# Generated by Django 4.2.6 on 2023-10-13 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="deleted_at",
        ),
    ]
