# Generated by Django 4.2.6 on 2023-10-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_deleted_at_remove_wallet_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ANALYST", "Analyst"), ("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
