# Generated by Django 4.2.6 on 2023-10-30 14:56

from django.db import migrations, models

import apps.base.enums


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Analyst", "Analyst"), ("User", "User"), ("Admin", "Admin")],
                default=apps.base.enums.Role["USER"],
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
