# Generated by Django 4.2.6 on 2023-10-30 21:28

from django.db import migrations, models

import apps.base.localstack


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to='/upload',
            ),
        ),
    ]
