# Generated by Django 4.2.6 on 2023-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="upload/"
            ),
        ),
    ]
