# Generated by Django 4.2.6 on 2023-10-31 13:42

import storages.backends.s3
from django.db import migrations, models

import apps.base.utils


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=apps.base.utils.upload_to,
            ),
        ),
    ]
